### ISSUE TITLE
release does not change io-package version

### ISSUE THREAD

**Issue by MeisterTR** [AlCalzone/release-script#102]
![2021-09-29_06h48_11](https://user-images.githubusercontent.com/6328382/135205014-01668e83-2158-45cc-bc8c-24bdc6821e0b.png)

**Comment by AlCalzone** [comment]
Pretty sure it does:
https://github.com/AlCalzone/ioBroker.zwave2/commit/7d2091fd4fdec89921bf2279534aa71ca8521765#diff-6ef04a9e675def1145dff7cc57420b1ea8bb3f6f5a5e4502cc5da0281981b472

Did you enable the `iobroker` plugin? In version 3, it is not on by default.

**Comment by MeisterTR** [comment]
ahh ok thanks..
