### ISSUE TITLE
Script only runs one, then it needs to be reinstalled

### ISSUE THREAD

**Issue by sbormann** [AlCalzone/release-script#114]
Hi,
i followed the insctructions on readme to install the script. It works fine, but only one time. When trying to run it again, it throws the following error:
````
pi@raspberrypi:/opt/iobroker/iobroker.iqontrol $ npm run release

> iobroker.iqontrol@2.0.0-rc1.2 release /opt/iobroker/iobroker.iqontrol
> release-script

sh: 1: release-script: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! iobroker.iqontrol@2.0.0-rc1.2 release: `release-script`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the iobroker.iqontrol@2.0.0-rc1.2 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2022-02-12T08_49_35_642Z-debug.log
````

Here is the complete log:
````
pi@raspberrypi:/opt/iobroker/iobroker.iqontrol $ cat /home/iobroker/.npm/_logs/2022-02-12T08_49_35_642Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'release' ]
2 info using npm@6.14.16
3 info using node@v14.19.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle iobroker.iqontrol@2.0.0-rc1.2~prerelease: iobroker.iqontrol@2.0.0-rc1.2
6 info lifecycle iobroker.iqontrol@2.0.0-rc1.2~release: iobroker.iqontrol@2.0.0-rc1.2
7 verbose lifecycle iobroker.iqontrol@2.0.0-rc1.2~release: unsafe-perm in lifecycle true
8 verbose lifecycle iobroker.iqontrol@2.0.0-rc1.2~release: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/iobroker/iobroker.iqontrol/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle iobroker.iqontrol@2.0.0-rc1.2~release: CWD: /opt/iobroker/iobroker.iqontrol
10 silly lifecycle iobroker.iqontrol@2.0.0-rc1.2~release: Args: [ '-c', 'release-script' ]
11 info lifecycle iobroker.iqontrol@2.0.0-rc1.2~release: Failed to exec release script
12 verbose stack Error: iobroker.iqontrol@2.0.0-rc1.2 release: `release-script`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:400:28)
12 verbose stack     at maybeClose (internal/child_process.js:1058:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
13 verbose pkgid iobroker.iqontrol@2.0.0-rc1.2
14 verbose cwd /opt/iobroker/iobroker.iqontrol
15 verbose Linux 5.10.63-v7l+
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "release"
17 verbose node v14.19.0
18 verbose npm  v6.14.16
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error iobroker.iqontrol@2.0.0-rc1.2 release: `release-script`
23 error spawn ENOENT
24 error Failed at the iobroker.iqontrol@2.0.0-rc1.2 release script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
````

After reinstalling the script (npm i release) it works, but again only one time. Can you help me fix that? 
Many thanks!

**Comment by AlCalzone** [comment]
Which version of the script are you using? Which npm version?

**Comment by AlCalzone** [comment]
Hmm sowas hab ich mit npm7 mal gesehen aber sollte eigentlich gefixt sein. Gib mir mal bitte den  link zum repo dann probier ich es selbst aus.

**Comment by sbormann** [comment]
Hi,
https://github.com/sbormann/ioBroker.iqontrol
Danke!

**Comment by AlCalzone** [comment]
Kann ich nicht reproduzieren...
```
$ npm -v
6.14.16
```

Dein repo geforkt und geklont, dann `npm ci` um den gleichen dependency-Stand wie du zu haben.
Dann 2 test-releases gemacht, ohne dass irgendwas verschwunden ist:

![grafik](https://user-images.githubusercontent.com/17641229/154098287-58258dfa-f7b8-43ce-b276-93c2c01060ca.png)

---

Ich probier die gleiche Prozedur nochmal auf Linux.

**Comment by AlCalzone** [comment]
Gleiches Spiel mit `npm@8.5.0`:
![grafik](https://user-images.githubusercontent.com/17641229/154099227-06bb2ff8-003f-4974-bc41-0b2e99c3686f.png)

🤷🏻‍♂️

**Comment by sbormann** [comment]
Ja genau, dort befindet sich die package-lock.json

Habe das mal vor zig Jahren in einem Tutorial-Video zur Adaperentwicklung gesehen und so übernommen. Hab das auch nie hinterfragt. Sollte das in einen anderen Ordner verschoben werden?

Am 15.02.2022 um 17:00 schrieb AlCalzone ***@***.***>:

﻿

Wait a minute... /opt/iobroker/?!

Vielleicht hat das was damit zu tun, dass du am "offenen Herzen" entwickelst.
Ich vermute mal dass im falschen Ordner nach dem release-script gesucht wird. Befindet sich in /opt/iobroker/iobroker.iqontrol eine package-lock.json?

**Comment by AlCalzone** [comment]
> Ja genau, dort befindet sich die package-lock.json

Befindet sich in `/opt/iobroker` ggf. noch eine, die aber das release-script nicht enthält? Ist nur ne Vermutung, aber ggf. stört diese Projekt-Hierarchie, sodass `npm install` einen Teil der dependencies löscht.

> Habe das mal vor zig Jahren in einem Tutorial-Video zur Adaperentwicklung gesehen und so übernommen. Hab das auch nie hinterfragt. Sollte das in einen anderen Ordner verschoben werden?

Ja früher war das der einzige Weg, in nem echten ioBroker zu arbeiten. Inzwischen gibt's den https://github.com/ioBroker/dev-server, der dir eine frische Instanz direkt im lokalen Adapter-Repo aufspannt. So funktioniert es definitiv.

**Comment by sbormann** [comment]
Ja, in ``/opt/iobroker`` befindet sich auch eine package-lock.json, ohne release-script. Soll ich in dem Verzeichnis auch einfach mal ein ``npm i -D @alcalzone/release-script`` ausführen?

**Comment by AlCalzone** [comment]
Kannste probieren, aber da gehörts eigentlich nicht hin.

Ich würde empfehlen, die Entwicklung von der ioBroker-Instanz zu trennen und dev-server zu nutzen. Mit dem kannst du die Instanz auch einfach "wegwerfen" und neu bauen, wenn was so richtig verkorkst ist.

**Comment by sbormann** [comment]
Damit hat es eben 2 x funktioniert. Denke, es ist damit erledit. Ich schau mir den dev-server an! Vielen Dank für die Hilfe!
