### ISSUE TITLE
prepatch versioning does not work

### ISSUE THREAD

**Issue by HGlab01** [AlCalzone/release-script#12]
I created a new prepatch version by using
npm run release prepatch.
A version 0.0.7-0 was created [OK]
Afterwards I did some changes and ran the command
npm run release prepatch
again. A version 0.0.8-0 was created [NOK], I expected a version 0.0.7-1

```
{
  _: [ 'prepatch' ],
  dry: true,
  all: true,
  '$0': 'node_modules\\@alcalzone\\release-script\\bin\\release.js'
}
Your branch has uncommitted changes that will be included in the release commit!
Consider adding them to a separate commit first.

bumping version 0.0.7-0 to prepatch version 0.0.8-0

dry run: not updating package files
dry run: I would execute this:
  npm install
  git add -A -- ":(exclude).commitmessage"
  git commit -F ".commitmessage"
  git tag v0.0.8-0
  git push
  git push --tags

done!
```

**Comment by AlCalzone** [comment]
That is correct. If you look at the documentation, it clearly states:
> Like patch, but to provide test versions before the final release. **WARNING: Using this multiple times increases the patch version each time.**

If you want to increase the suffix, you need to use `prerelease`, see https://github.com/AlCalzone/release-script#command-line
