### ISSUE TITLE
io-package.json is not updated anymore?

### ISSUE THREAD

**Issue by SKB-CGN** [AlCalzone/release-script#127]
Hi,
i did some changes to my project and the io-package.json is not updated with the new text from README.md.

When uploading them to Github, the Test and Release Runs fail due to version mismatch.

**Comment by AlCalzone** [comment]
You probably upgraded to v3 and didn't read the changelog?

https://github.com/AlCalzone/release-script#plug-ins

You'll have to install and enable the iobroker plug-in for this to work.

**Comment by SKB-CGN** [comment]
After changing the version to 3.5.9 it is working again.

Could it be the reason, that "dependabot" changed my package.json file?

**Comment by AlCalzone** [comment]
Yeah it's possible. You should review the changes it does though.

At least with the default configuration contained in the adapter template, major updates aren't merged automatically since they can contain such breaking changes.
