### ISSUE TITLE
Allow to specify that another command can be executed after updating version files/npm install and before commiting files

### ISSUE THREAD

**Issue by Apollon77** [AlCalzone/release-script#13]
In some adapters (admin, iot ...) where we e.g. have react stuff these files are also version specific (e.g. because of sentry) and are also committed to have the convenience to allow installing the adapter from GitHub.

This means after increasing the version in package/io-package and after npm install we need to run e.g. "npm run build" to update that and then also commit all the changed/removed/added files.

**Comment by AlCalzone** [comment]
This is supported in v1.7.0, which is now out. See https://github.com/AlCalzone/release-script#configuration-with-a-config-file for details.
