### ISSUE TITLE
io-package.json and package-lock.json not updated

### ISSUE THREAD

**Issue by Sneak-L8** [AlCalzone/release-script#131]
I ran "npm run release minor" the first time and changes were made and pushed to git.
But then a saw error in github action because of io-package.json and package-lock.json out of sync (version was only put in package.json, not in the two others, also release notes were missing in io-package.json).
CHANGELOG_OLD.md was created.

Log from console:
`check:git git status ok ✔
check:package package.json ok ✔
check:version Bumping version from 1.4.1 to 1.5.0 ✔

edit:package updating package.json version from 1.4.1 to 1.5.0
edit:changelog Updating changelog in README.md       

commit:package updating lockfile...
commit:git Commit message: chore: release v1.5.0`

What went wrong?

I first tried to do a dry run, but missed the fisrt "--". So I did a "npm run release minor --dry".
Can this be the reason?

**Comment by Sneak-L8** [comment]
Thanks for that hint. Now it works. 
But I fail at deployment:
`Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree.
error: Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means that the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count.`

Perhaps because previous releases were not fully done and deployed?

**Comment by AlCalzone** [comment]
That's sentry though. @Apollon77? Any idea what causes that?

**Comment by Apollon77** [comment]
Yes, this error happens when you tell sentry to "set the commits for this release" but sentry do not have that Repo linked in their config. That needs to be added once manually. I now did that for this epo.

SO the last release indeed was successfull just the commits were not assigned 8and maybe release not registered in sentry). should work from next release ongoing

**Comment by Sneak-L8** [comment]
Thanks für your help!
