### ISSUE TITLE
[Docu] option "nn" requires two minus signs to work

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/release-script#138]
Short form of --numNews (--nn) has two characters and hence requires two minus signs to work.

See PR #137

**Comment by AlCalzone** [comment]
Hmm the idea of these short forms is that you don't have to type two  --. We should probably choose another short form than `nn`.

**Comment by mcm1957** [comment]
Ok that would be ok for me too.

But currently the docu is wrong 😊 and I need some retries from time to time as -nn does not work without any visible error.

 

Feel free to change the option if you prefer. 

 

Martin

 

Von: AlCalzone ***@***.***> 
Gesendet: Mittwoch, 1. März 2023 10:07
An: AlCalzone/release-script ***@***.***>
Cc: Martin M. ***@***.***>; Author ***@***.***>
Betreff: Re: [AlCalzone/release-script] [Docu] option "nn" requires two minus signs to work (Issue #138)

 

Hmm the idea of these short forms is that you don't have to type two --. We should probably choose another short form than nn.
