### ISSUE TITLE
Add version information in headline

### ISSUE THREAD

**Issue by DutchmanNL** [AlCalzone/release-script#15]
Currently the placeholder provides possibility to add entries for changelog
## __WORK IN PROGRESS__
* Did some changes

Resulting in 

### 0.5.0 
* Did some changes

I would love to see a release summary, like : 

## __WORK IN PROGRESS__ >Major update of xxxx<
* Did some changes

Resulting in 

### 0.5.0 Major update of
* Did some changes

**Comment by AlCalzone** [comment]
Supported in `v1.8.0`
