### ISSUE TITLE
[iobroker plugin] Some author names are not removed

### ISSUE THREAD

**Issue by klein0r** [AlCalzone/release-script#158]
e.g. `René`

https://github.com/AlCalzone/release-script/blob/111e796532a1d6410e4e61662d98fd6ac7c01faa/packages/plugin-iobroker/src/tools.ts#L17

see https://github.com/ioBroker/ioBroker.admin/issues/2314

**Comment by AlCalzone** [comment]
The regex should probably use the unicode character classes instead of just `a-z`

**Comment by klein0r** [comment]
Suggestion:

`^[ \t]*[\*\-][ \t]*\([a-z0-9\p{L}\p{M}\-_,;&\+\/ ]+\)[ \t]*`

(added `\p{L}\p{M}`)

Matches

```
* (Jürgen) Line 1
* (Jérôme) Line 2
* (René) Line 3
* (Burić) Line 4
* (Çoban) Line 5
* (Jörg) Line 6
* (Keßler) Line 7
``

**Comment by klein0r** [comment]
@AlCalzone Please release a new version

**Comment by AlCalzone** [comment]
Sorry, 3.7.1 is coming

**Comment by klein0r** [comment]
@AlCalzone Thank you, but the release failed due to node 14.x tests. see https://github.com/AlCalzone/release-script/pull/169

https://github.com/AlCalzone/release-script/actions/runs/9472530936/job/26098045386
