### ISSUE TITLE
[new feature] New parameter in `.releaseconfig.json` - indent

### ISSUE THREAD

**Issue by GermanBluefox** [AlCalzone/release-script#174]
We decided in `@iobroker/eslint-config`, that indent in JSON files will be 4 spaces.
After each release the `package.json` reverts it indent to 2 spaces.

Suggestion: add to `.releaseconfig.json` the parameter for indent in JSON files:
```
{
    "plugins": ["license"],
    "exec": {
        "before_commit": "npm run build"
    },
    "indent": 4
}
```

**Comment by AlCalzone** [comment]
Running an `npm install` causes `npm` to format `package.json` and `package-lock.json` with 2-space indentation. So even if the release script formats the files in a way that matches a linter config, you'll be fighting `npm` instead.

IMO it's best not to and just accept that the npm-related files are indented with 2 spaces.
