### ISSUE TITLE
remove name from new when mentioned in readme

### ISSUE THREAD

**Issue by DutchmanNL** [AlCalzone/release-script#2]
Currently lines in readme for changelog an copy/pasted with line breaks 1;1

Readme structure mostly is : 

### __Veresion__
* (Author) >information<
* (Author) >information<

the lines * (Author) should not be copied into the news as it looks somehow strange :) 

<img width="905" alt="Schermafbeelding 2020-04-24 om 09 48 11" src="https://user-images.githubusercontent.com/7318445/80187914-b7d4d980-8610-11ea-9822-764f7f8ed8cd.png">

**Comment by AlCalzone** [comment]
Would you mind doing a test run before I release this to the public?
Just install this dependency from github:
```
npm i -D AlCalzone/release-script
```
and try it out with a changelog that contains the author name.
