### ISSUE TITLE
Add argument to force git commit of non committed local items

### ISSUE THREAD

**Issue by DutchmanNL** [AlCalzone/release-script#3]
it would be helpful if

> This is a dry run. The full run would fail due to uncommited changes

Would provide an argument option to commit the local changes

same for 

> This is a dry run. The full run would fail due to a diverged branch

Please add argument to force commit to git

**Comment by AlCalzone** [comment]
The first one is okay, the 2nd requires a merge of the remote changes which the script can't do for you.

**Comment by DutchmanNL** [comment]
> The first one is okay, the 2nd requires a merge of the remote changes which the script can't do for you.

if we can do option 1 I am already very happy

**Comment by AlCalzone** [comment]
v1.3.0 contains a new parameter `--all` to include uncommitted changes. The error messages have been improved to mention this new parameter.
