### ISSUE TITLE
Is it possible to stop action on github

### ISSUE THREAD

**Issue by GermanBluefox** [AlCalzone/release-script#39]
During the release first will be changed all the versions and then the tag will be given.
That creates 2 pipeline runs on github. 
![image](https://user-images.githubusercontent.com/4582016/102023669-7d7d9f80-3d8d-11eb-9ff4-282d83d91739.png)

First "master" pipeline is not required. Is it possible to stop it somehow? 
In this script, in actions itself?

**Comment by AlCalzone** [comment]
You should be able to achieve this by adding the following condition to all other jobs:
```
if: |
  !(
    github.event_name == 'push' &&
    github.event.base_ref == 'refs/heads/master' &&
    !startsWith(github.event.head_commit.message, 'chore: release')
  )
```
