### ISSUE TITLE
option to define git commit message

### ISSUE THREAD

**Issue by DutchmanNL** [AlCalzone/release-script#5]
I would like that we can modify the commit message as currently "chore: release xxx" does not mention anything

Would be great if : 

- we can keep it or provide a commit message by command line
- taking thee "readme" itms of news also as descriton into the git commit.

this would result in commits like : 

<img width="1009" alt="Schermafbeelding 2020-04-24 om 10 20 47" src="https://user-images.githubusercontent.com/7318445/80190912-45b2c380-8615-11ea-89a9-10869a07d3e1.png">

which like more in comparison with 

<img width="1030" alt="Schermafbeelding 2020-04-24 om 10 21 22" src="https://user-images.githubusercontent.com/7318445/80190969-595e2a00-8615-11ea-982b-b7e3b17d35e6.png">

**Comment by AlCalzone** [comment]
I don't agree 100%, because the first line of a commit should be short and not exceed 72 characters. 

The changelog could however be added in the additional lines so they are displayed like the last two lines in your first screenshot

**Comment by DutchmanNL** [comment]
> I don't agree 100%, because the first line of a commit should be short and not exceed 72 characters.

aggree, but that limit is ok as example its handy to see the commits and related change : 

<img width="1052" alt="Schermafbeelding 2020-04-24 om 11 34 43" src="https://user-images.githubusercontent.com/7318445/80197936-aa731b80-861f-11ea-955a-6968f8660b67.png">

**Comment by AlCalzone** [comment]
What about this?

> The changelog could however be added in the additional lines so they are displayed like the last two lines in your first screenshot

In that case you would get the [...] button like in your other commits, which would then show the changelog.

**Comment by DutchmanNL** [comment]
> What about this?

yes as mentioned as second demand that would be great to have the description, however having a manfulll commit message makes sense I guess also :) (of course with limited characters)

**Comment by AlCalzone** [comment]
What is not meaningful about `Release vX.Y.Z`?

**Comment by DutchmanNL** [comment]
> What is not meaningful about `Release vX.Y.Z`?

ist only the number, no relation to the "what" so yes technical speaking it is meaningful but enduser speaking as a human person it not :)
I don't know what version 0.5.2 is but 0.5.3 Change admin Interface 
is something I understand

**Comment by AlCalzone** [comment]
Well, ideally your previous commit messages should already contain what you changed (and more importantly, when!). If you want to know exactly what changed compared to the previous release, you can click on [...] if we include the changelog as details.

**Comment by DutchmanNL** [comment]
I agree, so I think this is more documentation and way of working.
so

- commits are commits with functionality
- releases are releases and can be managed by the script
- lets not confused releases and commits (basically I did that here....)

so in that cases, as summary, I suggest to : 

- keep the title as is
- moved the parts from readme to the description (as discussed above)

that's it, rest is own commit management

**Comment by DutchmanNL** [comment]
works like a charm thank you !
