### ISSUE TITLE
Release script misses to update Adapter-version in widget

### ISSUE THREAD

**Issue by Excodibur** [AlCalzone/release-script#51]
It seems like the script does not increase the release-number in the widget JS code. At least the adapter-creator sets up this version here:
https://github.com/ioBroker/create-adapter/blob/546189cd9675a411ef11ce05def6daf3195956f5/templates/widgets/template.js.ts#L43

In theory developers could implement version-specific information anywhere in the code, but perhaps it is worth to support at least verison-number-increases in widgets created "the offical way".

**Comment by AlCalzone** [comment]
It's a little bit complicated but possible now with `v3.3.0` and these replacement patterns.
https://github.com/AlCalzone/release-script#replace-the-version-in-additional-files---versionfiles


```jsonc
// .releaseconfig.json
{
  // ...
  "versionFiles": [
    ["widgets/**/*.*", "(?<=version: \")(.*?)(?=\")"]
  ]
}
```
