### ISSUE TITLE
Support star for placeholders

### ISSUE THREAD

**Issue by UncleSamSwiss** [AlCalzone/release-script#52]
Prettier rewrites `__` to `**` thus the "Work in progress" placeholder is no longer detected.

Original:

```markdown
# Changelog
<!--
	Placeholder for the next version (at the beginning of the line):
	## __WORK IN PROGRESS__
-->

## __WORK IN PROGRESS__
```

When prettified:
```markdown
# Changelog

<!--
	Placeholder for the next version (at the beginning of the line):
	## __WORK IN PROGRESS__
-->

## **WORK IN PROGRESS**
```

One can add CHANGELOG.md to .prettierignore, but this is not a nice solution for README.md.

Thus it would be great, if both `__` and `**` were supported as placeholder escape sequences.

I would also suggest to change the default (including the documentation) to `**` as this seems to be the way forward for markdown (at least according to prettier).

**Comment by AlCalzone** [comment]
Included in v1.10.0
