### ISSUE TITLE
Enhancement: Update year in copyright and license

### ISSUE THREAD

**Issue by foxriver76** [AlCalzone/release-script#67]
I often forget to update copyright and license, when doing a new release in a new year. At some timepoint when adapter checker (ioBroker related) runs I will then get noticed and have to adapt many adapter theoretically.. or I just won't do it.  Far from ideal.

Maybe it would be an option that release script detects that e.g. copyright is `2018 - 2020` and asks if I want to update to `2021` or just do i w/o asking. But sometimes there a previous maintainers listed, then it should be asked or detected who is the most recent one.

**Comment by AlCalzone** [comment]
Fixed in https://github.com/AlCalzone/release-script/commit/b8f45158b7e757c7112e250c452c2cf68dee3aba using the new `license` plugin:

![grafik](https://user-images.githubusercontent.com/17641229/133515281-5e0611cf-956b-4323-b502-d6550494cbbb.png)

**Comment by AlCalzone** [comment]
released in `v3.1.0`
