### ISSUE TITLE
--all option is ignored

### ISSUE THREAD

**Issue by Jey-Cee** [AlCalzone/release-script#84]
In the screenshot you can see that the option --all is called but seems to be ignored wihle error is still there.
![image](https://user-images.githubusercontent.com/16007760/127746220-2615d5a9-b4af-40c7-a1eb-ccf0c4484125.png)

**Comment by AlCalzone** [comment]
https://github.com/AlCalzone/release-script#include-other-changes-in-the-release-commit

The correct command is 
```
npm run release patch -- --all
```

What you wrote causes `npm` to intercept the `patch` and `all` options for itself.
