### ISSUE TITLE
Enhancement: Allow to spit release in two steps: "Content preparation" and "Release"

### ISSUE THREAD

**Issue by Apollon77** [AlCalzone/release-script#89]
it would be cool to allow a "prepare" call which is doing all the checks and increases version and prepares changelog and such, but DO NOT commit it. Then the developer can e.g. manually correct the io-package translations or such. Then he execites the "finalize" command which then commits these files and actually does the release.

**Comment by AlCalzone** [comment]
This is now possible in 2c7ef2fb4aa428fab5f26084fe1e82eec82ea625 with the new `manual-review` plugin:
![are you done](https://user-images.githubusercontent.com/17641229/133517199-4eba3cea-00c4-4da0-87f3-3502ffba67b8.gif)

**Comment by AlCalzone** [comment]
released in `v3.1.0`
